project_id = "hpyvadzxmutbbzwgmecv"

[functions.generate-lessons]
verify_jwt = false

[functions.curative-assistant]
verify_jwt = false

[functions.embed-knowledge]
verify_jwt = false

[functions.search-context]
verify_jwt = false
